server:
  port: 8081

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:postgresql://localhost:5432/gambling
    username: elianaorfao
    password: mypostgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    sql:
      init:
        mode: always

